interface=wlxe84e06aed7ca
bind-interfaces

dhcp-range=192.168.50.10,192.168.50.50,255.255.255.0,12h
dhcp-option=3,192.168.50.1
dhcp-option=6,192.168.50.1
dhcp-authoritative

# Captive portal DNS redirection:
# every domain resolves to the attack AP address.
address=/#/192.168.50.1

log-dhcp
log-queries
